### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by NinjaCXX** [Embodied-Codebook/embodied-codebook.github.io#1]
Thanks for your great work. When will you release the code? @Ainaz99

**Comment by Ainaz99** [comment]
Hi @NinjaCXX ! The code will be released sometime in the next 2 weeks.

**Comment by Ainaz99** [comment]
Hello! 
The code is released here: https://github.com/allenai/procthor-rl/tree/main !

**Comment by NinjaCXX** [comment]
Thanks for your sharing. God bless you.
